### PR TITLE
BLS12-381 powersoftau new and contribute bugs fixed

### PR DESCRIPTION
**Pull request by glamperd**
The `snarkjs powersoftau new bls12-381 ...` command had an error: bls12381.q and r  undefined. This PR includes the fix offered in #30.

With that fix, the command `snarkjs powersoftau contribute ...` failed with a `curve not supported` error. See #36 

This PR includes fixes for both the above.

### CODE REVIEW

**Comment by glamperd** [comment]
The fix is based on comments in [this big-integer issue](https://github.com/peterolson/BigInteger.js/issues/210). When creating a BigInt from another BigInt, convert to string first, otherwise the conversion is via a JS number, causing a loss of precision.

**Comment by phated** [comment]
@glamperd Can you please restore the package-lock.json file that you seem to have deleted?

**Comment by phated** [comment]
You can also remove the `build/main.cjs` changes, as that file is generated during release. Thanks! 🙏

**Review by phated — APPROVED** [review]
I removed the changes in those 2 files. This looks good to me 👍  Thanks!

**Pull request merged**
