### PR TITLE
Fix undefined `q` and `r` in `buildBls12381`

### PR DESCRIPTION
**Pull request by piotr-roslaniec**
Fixes issue described in https://github.com/iden3/snarkjs/issues/122

### CODE REVIEW

**Comment by glamperd** [comment]
I find that this fixes the 'powersoftau new' command, but 'powersoftau contribute' then fails when adding to the 'new' file. This is the error: ```snarkJS: Error: Curve not supported: 4002409555221667610661788685990436838824310417315709160196267947217350388461752218928110433526561144555515641069568
    at getCurveFromQ (file:///home/root/snarkjs/src/curves.js:28:15)
    at Module.readPTauHeader (file:///home/root/snarkjs/src/powersoftau_utils.js:61:25)
    at async Module.contribute (file:///home/root/snarkjs/src/powersoftau_contribute.js:37:43)
    at async Object.powersOfTauContribute [as action] (file:///home/root/snarkjs/cli.js:755:12)
    at async clProcessor (file:///home/root/snarkjs/src/clprocessor.js:72:27)
 ```

**Comment by glamperd** [comment]
When logged in base16, the q value is this: `Error: Curve not supported>>>: 1a0111ea397fe700000000000000000000000000000000000000000000000000000000000000000000000000000000000`. The beginning of that number is correct. It's as if the q value is truncated when written to the file.

**Comment by glamperd** [comment]
I have a fix. It was forming the curve q & r values by directly referring to the q & r values from the curve params. This is known in big-integer to cause a loss of precision. Form the values by first converting to string. It remains a mystery why BLS12-381 was failing but BN128 was working without the fix.

**Comment by piotr-roslaniec** [comment]
@glamperd Thank you for investigating this. I'm closing this PR in favor of your changes in #37.

**Comment by piotr-roslaniec** [comment]
@glamperd Thank you for investigating this. I'm closing this PR in favor of your changes in #37.

**Pull request closed without merging**
